import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import java.io.IOException;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class PdfTest {
    public static void main(String[] args) {
        String fileName = "ExpenseTrackerReport_" +
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss")) +
                ".pdf";

        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage();
            document.addPage(page);
            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 24);

                contentStream.beginText();
                contentStream.newLineAtOffset(100, 750);
                contentStream.showText("Expense Tracker Report");
                contentStream.endText();

                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 16);
                contentStream.beginText();
                contentStream.newLineAtOffset(100, 700);
                contentStream.showText("Generated by: [Your Name Here]"); // ← PUT YOUR NAME HERE
                contentStream.endText();

                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                contentStream.beginText();
                contentStream.newLineAtOffset(100, 670);
                contentStream.showText("Generated on: " + LocalDateTime.now().format(
                        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
                contentStream.endText();

                contentStream.moveTo(100, 650);
                contentStream.lineTo(500, 650);
                contentStream.stroke();

                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 14);
                contentStream.beginText();
                contentStream.newLineAtOffset(100, 620);
                contentStream.showText("This is a test PDF generated by Apache PDFBox.");
                contentStream.endText();

                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                String[] points = {
                        "- PDF generation is working correctly",
                        "- Fonts and formatting are functional",
                        "- Ready to implement full reporting",
                        "- Next: Connect to TransactionService",
                        "- Then: Add charts and tables"
                };

                int yPosition = 580;
                for (String point : points) {
                    contentStream.beginText();
                    contentStream.newLineAtOffset(120, yPosition);
                    contentStream.showText(point);
                    contentStream.endText();
                    yPosition -= 25;
                }

                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_OBLIQUE), 10);
                contentStream.beginText();
                contentStream.newLineAtOffset(100, 100);
                contentStream.showText("Confidential - Generated by Expense Tracker v1.0");
                contentStream.endText();
            }

            document.save(fileName);
            System.out.println(" PDF created successfully: " + fileName);
            System.out.println("📁 File saved to: " + Paths.get(fileName).toAbsolutePath());

        } catch (IOException e) {
            System.err.println("❌ PDF creation failed: " + e.getMessage());
            e.printStackTrace();
        }
    }
}